env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    tsx: true
  project: tsconfig.json
plugins:
  - react
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/consistent-type-definitions":
    - "error"
    - "type"
